name: 'Secret Scan'
description: 'Fail the job if gitleaks finds a committed secret'
runs:
  using: 'composite'
  steps:
    - name: Run gitleaks
      uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
      env:
        # Requires caller job to have permissions: { contents: read }
        GITHUB_TOKEN: ${{ github.token }}
        GITLEAKS_ENABLE_COMMENTS: 'false'
