name: Test - Secret Scan
on: push
jobs:
  should-fail:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/secret-scan
