name: Test - Python CI
on: [push, pull_request]
jobs:
  call-python-ci:
    uses: ./.github/workflows/python-ci.yml
    with:
      working-directory: test-fixtures/python-sample
    secrets: inherit
